name: local
proxy: # these have to match the name above
  appserver:
    - local.lndo.site
  pma:
    - pma.local.lndo.site
  mailhog:
    - mh.local.lndo.site
config:
  php: "8.0"
services:
  appserver:
    overrides:
      environment:
        # General site information
        wpengine_name: local
        repo: git@github.com:powersdev/scaffold
        multisite: no
        # SSH Keys
        repo_ssh_key: id_ed25519
        wpe_ssh_key: id_ed25519
